### ISSUE TITLE
Add Confluent images to manifest

### ISSUE THREAD

**Issue by potto007** [raft-tech/airgapped-kafka-k8s#4]
Prepend to the list images the Confluent images and their respective details provided by Brent at Confluent:

Confluent is working with IronBank to certify into their IronBank Container repo the following 5.5.2 containers:
- [x] cp-zookeeper-5.5.x
- [x] cp-kafka-5.5.x
- [x] cp-schemaregistry-5.5.x
- [x] cp-ksqldb-server-5.5.x
- [x] cp-ksqldb-cli-5.5.x

**Comment by BarakStout** [comment]
Resolved via #5
